<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Аукцион окончен</title>
    <style>
        h1 {
            color: cadetblue;
        }
        h2 {
            color: red;
        }
        h3 {
            color: green;
        }
    </style>
</head>
<body>
<h1><a href="http://localhost/user/${winner_id}">Победитель</a></h1>
<h2><a href="http://localhost/auction/${auction_id}">Лот</a></h2>
</body>
</html>
